### ISSUE TITLE
Top ページのお知らせ一覧をイベント一覧にする

### ISSUE THREAD

**Issue by arumakan1727** [szpp-dev-team/szpp-dev-team.github.io#16]

**Comment by arumakan1727** [comment]
見出しと個々のイベント要素とで水色の横線のデザインがかぶっててダサくなる...

![image](https://user-images.githubusercontent.com/33191176/159163750-e63c0969-f4a7-4cc9-9819-571488f20663.png)

**Comment by earlgray283** [comment]
水色とマッチする色なんだろう・・・

**Comment by arumakan1727** [comment]
お、見てくれてたのか

とりあえずこれでヨシにすることにした

![image](https://user-images.githubusercontent.com/33191176/159167655-7815f09d-189d-4a83-bed9-6ccdc34df8d7.png)
